"use client";
import { useState } from "react";
import useSWR from "swr";
import Link from "next/link";
import { ArrowLeft, FileText, Folder, Download, Workflow } from "lucide-react";
import { api } from "@/lib/api";
import { useProject } from "@/lib/hooks";
import { ACTIVITY_LABELS } from "@/lib/agent-experience";
import { PageBody, PageHeader } from "./page-header";
import { ErrorState } from "./states";
import { WorkStatus } from "./business-kanban";
import { PROJECT_STAGE } from "./projects-view";
import { cn } from "@/lib/utils";

const GROUP_LABEL: Record<string, string> = { prd: "PRD & konteks", meetings: "Catatan meeting", legal: "Kontrak & legal", qa: "Laporan QA", docs: "SOP & panduan", handover: "Serah terima", content: "Studi kasus" };
const CONTEXT_LABEL: Record<string, string> = { summary: "Ringkasan", objective: "Tujuan", scope: "Lingkup", openQuestions: "Perlu dikonfirmasi", source: "Sumber" };
const date = (value: string) => new Date(value).toLocaleString("id-ID", { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
export function ProjectDetailView({ id }: { id: string }) {
  const { data, error } = useProject(id);
  const [tab, setTab] = useState("context");
  const [selected, setSelected] = useState<string | null>(null);
  const [group, setGroup] = useState("all");
  const document = useSWR(selected ? ["project-document", id, selected] : null, () => api.projectDocument(id, selected!), { refreshInterval: 5000 });
  const download = () => {
    if (document.data?.content == null) return;
    const url = URL.createObjectURL(new Blob([document.data.content], { type: "text/plain;charset=utf-8" }));
    const link = window.document.createElement("a"); link.href = url; link.download = document.data.name; link.click(); URL.revokeObjectURL(url);
  };
  return <><PageHeader title={data?.project.title ?? "Folder proyek"} description={data ? `${data.client?.company ?? data.client?.name ?? "Proyek"} · ${PROJECT_STAGE[data.project.stage] ?? data.project.stage}` : "Konteks dan hasil pekerjaan proyek"} actions={<Link className="inline-flex items-center gap-2 rounded-lg border bg-card px-3 py-2 text-xs" href="/projects"><ArrowLeft className="size-3.5" />Semua folder</Link>} />
    <PageBody>{error ? <ErrorState message={error.message} /> : !data ? <div className="h-80 animate-pulse rounded-xl bg-muted" /> : <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-card px-4 py-3"><div className="flex flex-wrap items-center gap-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-2"><Folder className="size-4" />{data.documents.length} dokumen</span><span>Diperbarui {date(data.project.updatedAt)}</span></div><Link className="inline-flex items-center gap-2 rounded-lg bg-black px-3 py-2 text-xs text-white" href={`/workflow?case=${encodeURIComponent(`project:${id}`)}`}><Workflow className="size-3.5" />Lihat workflow</Link></div>
      <div role="tablist" aria-label="Isi folder proyek" className="flex flex-wrap gap-2">{[{ id: "context", label: "Konteks" }, { id: "documents", label: `Dokumen (${data.documents.length})` }, { id: "activity", label: "Jejak proses" }, { id: "invoices", label: `Invoice (${data.invoices.length})` }].map((item) => <button key={item.id} role="tab" aria-selected={tab === item.id} aria-controls={`project-${item.id}`} id={`tab-${item.id}`} onClick={() => setTab(item.id)} className={cn("rounded-lg px-4 py-2 text-sm", tab === item.id ? "bg-black text-white" : "border bg-card text-muted-foreground hover:bg-muted")}>{item.label}</button>)}</div>
      <section role="tabpanel" id={`project-${tab}`} aria-labelledby={`tab-${tab}`} className="min-w-0">
      {tab === "context" && <div className="grid gap-5 lg:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]"><div className="space-y-5 rounded-xl border bg-card p-5 sm:p-6"><h2 className="font-medium">Konteks proyek</h2>{Object.keys(data.context).length ? Object.entries(data.context).map(([key, value]) => <div key={key}><h3 className="text-xs text-muted-foreground">{CONTEXT_LABEL[key] ?? key}</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7">{Array.isArray(value) ? value.join("\n") : value}</p></div>) : <p className="text-sm leading-7 text-muted-foreground">Kebutuhan dan lingkup proyek tersimpan dalam PRD. Buka dokumen untuk membaca konteks lengkap dari Scoper.</p>}{data.documents.filter((file) => file.group === "prd" || file.group === "meetings").map((file) => <button key={file.path} onClick={() => { setSelected(file.path); setGroup("all"); setTab("documents"); }} className="flex w-full items-center gap-3 rounded-xl border p-4 text-left hover:bg-muted"><FileText className="size-5 shrink-0 text-muted-foreground" /><span className="min-w-0 flex-1 break-words text-sm">{file.name}<span className="mt-1 block text-xs text-muted-foreground">{GROUP_LABEL[file.group]}</span></span><span className="text-xs text-muted-foreground">Buka</span></button>)}</div><aside className="h-fit space-y-5 rounded-xl border bg-card p-5"><h2 className="text-sm font-medium">Tentang proyek</h2>{[{ label: "Klien", value: data.client?.name ?? "Belum ditautkan" }, { label: "Perusahaan", value: data.client?.company ?? "—" }, { label: "Tahap", value: PROJECT_STAGE[data.project.stage] ?? data.project.stage }, { label: "Dibuat", value: date(data.project.createdAt) }].map((item) => <div key={item.label}><p className="text-xs text-muted-foreground">{item.label}</p><p className="mt-1 break-words text-sm leading-6">{item.value}</p></div>)}{data.client?.leadId && <Link className="inline-block text-sm underline underline-offset-4" href={`/leads/${encodeURIComponent(data.client.leadId)}`}>Percakapan & kebutuhan klien</Link>}</aside></div>}
      {tab === "documents" && <div className="grid items-start gap-5 lg:grid-cols-[280px_minmax(0,1fr)]"><div className="space-y-4 rounded-xl border bg-card p-4"><h2 className="text-sm font-medium">Dokumen proyek</h2><select value={group} onChange={(event) => setGroup(event.target.value)} aria-label="Jenis dokumen" className="w-full rounded-lg border bg-card p-2 text-xs"><option value="all">Semua dokumen</option>{Object.entries(GROUP_LABEL).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>{data.documents.filter((file) => group === "all" || file.group === group).map((file) => <button key={file.path} onClick={() => setSelected(file.path)} className={cn("flex w-full items-start gap-2 rounded-lg p-3 text-left", selected === file.path ? "bg-black text-white" : "hover:bg-muted")}><FileText className="mt-0.5 size-4 shrink-0" /><span className="min-w-0 break-words text-xs leading-5">{file.name}<span className="block opacity-60">{GROUP_LABEL[file.group]}</span></span></button>)}{!data.documents.filter((file) => group === "all" || file.group === group).length && <p className="text-xs leading-6 text-muted-foreground">Belum ada dokumen di kategori ini.</p>}</div><div className="min-w-0 rounded-xl border bg-card p-5 sm:p-6">{document.error ? <ErrorState message={document.error.message} /> : selected ? document.data ? <><div className="mb-5 flex flex-wrap items-start justify-between gap-3 border-b pb-4"><div className="min-w-0"><h3 className="break-words text-sm font-medium">{document.data.name}</h3><p className="mt-1 text-xs text-muted-foreground">{date(document.data.updatedAt)}</p></div>{document.data.content != null && <button onClick={download} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs"><Download className="size-3.5" />Unduh</button>}</div>{document.data.tooLarge ? <p className="text-sm text-muted-foreground">Dokumen melebihi batas pratinjau 512 KB.</p> : <pre className="max-h-[65vh] overflow-y-auto whitespace-pre-wrap break-words font-sans text-sm leading-7">{document.data.content}</pre>}</> : <p className="text-sm text-muted-foreground">Memuat dokumen…</p> : <div className="py-16 text-center"><FileText className="mx-auto mb-3 size-8 text-muted-foreground/40" /><p className="text-sm text-muted-foreground">Pilih dokumen untuk membaca hasil pekerjaan.</p></div>}</div></div>}
      {tab === "activity" && <div className="grid gap-5 lg:grid-cols-2"><div className="space-y-4 rounded-xl border bg-card p-5"><h2 className="text-sm font-medium">Pekerjaan proyek</h2>{data.jobs.map((job) => <div key={job.id} className="space-y-2 rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm">{ACTIVITY_LABELS[job.type] ?? job.type}</p><WorkStatus state={job.status === "queued" ? "waiting" : job.status === "failed" ? "blocked" : job.status} /></div><p className="text-xs text-muted-foreground">{date(job.updatedAt)} · #{job.id.slice(0, 8)}</p></div>)}{!data.jobs.length && <p className="text-sm text-muted-foreground">Belum ada pekerjaan tercatat.</p>}</div><div className="space-y-4 rounded-xl border bg-card p-5"><h2 className="text-sm font-medium">Jejak audit</h2>{data.events.map((event) => <div key={event.id} className="border-l pl-4"><p className="text-sm">{ACTIVITY_LABELS[event.type] ?? event.type}</p><p className="mt-1 text-xs text-muted-foreground">{date(event.at)} · #{event.id}</p></div>)}{!data.events.length && <p className="text-sm text-muted-foreground">Belum ada laporan tercatat.</p>}</div></div>}
      {tab === "invoices" && <div className="space-y-4 rounded-xl border bg-card p-5"><h2 className="text-sm font-medium">Pembayaran proyek ini</h2>{data.invoices.map((invoice) => <div key={invoice.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-4"><div><p className="text-sm font-medium">{invoice.kind === "dp" ? "Uang muka (DP)" : invoice.kind === "retainer" ? "Retainer" : "Pelunasan"}</p><p className="mt-2 text-xs text-muted-foreground">{invoice.paidAt ? `Dibayar ${date(invoice.paidAt)}` : invoice.dueAt ? `Jatuh tempo ${date(invoice.dueAt)}` : "Belum ada tanggal pembayaran"}</p></div><div className="space-y-2 text-right"><p className="text-sm font-medium tabular-nums">{new Intl.NumberFormat("id-ID", { style: "currency", currency: invoice.currency }).format(invoice.amount)}</p><span className="text-xs text-muted-foreground">{invoice.status === "paid" ? "Lunas" : invoice.status === "sent" ? "Menunggu pembayaran" : invoice.status === "draft" ? "Draf" : invoice.status}</span></div></div>)}{!data.invoices.length && <p className="text-sm leading-6 text-muted-foreground">Belum ada invoice untuk proyek ini.</p>}</div>}
      </section>
    </div>}</PageBody></>;
}

